### ISSUE TITLE
How to specify specific commit/tags?

### ISSUE THREAD

**Issue by hakonhagland** [devanshshukla99/sphinx-versioned-docs#70] opened 2024-03-06 22:38 UTC
We have a large repository which contains sphinx documentation in a `docs` folder. We plan to host the documentation on GitHub pages. Commits usually go to the master branch, but most commits are not related to the documentation. How can I use this command to select certain commits/tags that are related to updating documentation (that is: changes to the docs folder)? How do I specify a sphinx version for these commits?

**Comment by hakonhagland** [comment] 2024-03-06 23:16
> How can I use this command to select certain commits/tags that are related to updating documentation?

Did some more testing and found that I have to tag the commit first. So the following worked from the root of repository with documentation in the `docs` folder (I created a branch "sphinx_versioned" for testing purposes):

```
$ sphinx-versioned -b "sphinx_versioned, v1.0, v2.0" -m sphinx_versioned 
| SUCCESS  | - latched into the git repo
| SUCCESS  | - located conf.py
| INFO     | - Selecting tag for further processing: sphinx_versioned
| CRITICAL | - Branch not found: ``, use `--force` to force the build
| INFO     | - Selecting tag for further processing: v1.0
| CRITICAL | - Branch not found: ``, use `--force` to force the build
| INFO     | - Selecting tag for further processing: v2.0
| INFO     | - pre-building: sphinx_versioned
| SUCCESS  | - pre-build succeded for sphinx_versioned :)
| INFO     | - pre-building: v1.0
| SUCCESS  | - pre-build succeded for v1.0 :)
| INFO     | - pre-building: v2.0
| SUCCESS  | - pre-build succeded for v2.0 :)
| SUCCESS  | - Prebuilding successful for sphinx_versioned, v1.0, v2.0
| INFO     | - Building: sphinx_versioned
| INFO     | - Theme: sphinx_rtd_theme
| SUCCESS  | - build succeded for sphinx_versioned ;)
| INFO     | - Building: v1.0
| INFO     | - Theme: sphinx_rtd_theme
| SUCCESS  | - build succeded for v1.0 ;)
| INFO     | - Building: v2.0
| INFO     | - Theme: sphinx_rtd_theme
| SUCCESS  | - build succeded for v2.0 ;)
| SUCCESS  | - main branch: `sphinx_versioned`; generating top-level `index.html`

 Successfully built sphinx_versioned, v1.0, v2.0 
```

What does the message 
```
| CRITICAL | - Branch not found: ``, use `--force` to force the build`
```
mean here?

**Comment by devanshshukla99** [comment] 2024-03-07 12:05
Hi!
Thank you for pointing it out, it's actually a minor bug in `v1.3.1` which I realised a little too late.

It's fixed on the dev branch (main) if you wanna give it a try.
Anyways, I'll release a minor revision `v1.3.2` to make sure its fixed on PyPi and conda.

Your built documentation should be just fine so you can safely ignore it.

**Comment by devanshshukla99** [comment] 2024-03-07 12:06
Besides, this `branch not found` message is actually intended for building the git head detached commits (not tagged ones).

Essentially, it'll not check if the specified branch in `-b` is actually a branch or not, so it could be used to build documentations for detached commits.

This is useful in testing and stuff but the commit name is a mess in the version selector menu.

**Comment by devanshshukla99** [comment] 2024-03-07 22:46
> How can I use this command to select certain commits/tags that are related to updating documentation (that is: changes to the docs folder)?

This is not possible in the current implementation, however, probably an interesting thing to add in the future!

> How do I specify a sphinx version for these commits?

By design, all the commits/branches/tags will be built using the already installed `sphinx`.

This project already contains a monkey-patch (enabled by `--sphinx-compatibility`) for the deprecated func `add_stylesheet`. So,
if any issue arises somewhere, kindly open a new issue and I'll try to get it resolved.

**Closed** 2024-03-07 22:55 UTC
Labels: bug
